version: '3.8'

services:
  db:
    image: 'postgres:15'
    volumes:
      - 'db:/var/lib/postgresql/data'
    ports:
      - '5432:5432' #host:container
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=bitly_clone
      - POSTGRES_PASSWORD=password

  # api:
  #   depends_on:
  #     - 'db'
  #   build: .
  #   ports:
  #     - '3001:3001' #host:container
  #   volumes:
  #     - ./:/usr/src/app
  #   command: bash -c "node index.js"
  #   # command: bash -c "npm install -g nodemon && yarn install && nodemon --inspect=0.0.0.0:9222 index.js"
  #   environment:
  #     # WEB SERVER
  #     - NODE_ENV=local
  #     - PORT=3001
  #     # DATABASE
  #     - DATABASE_URL=postgres://bitly_clone:password@db:5432/bitly_clone
  link_tracker:
    depends_on:
      - 'db'
    build:
      context: ./link_tracker
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3001' #host:container
    volumes:
      - ./link_tracker:/app
    command: bash -c "pnpm install && npx prisma generate && pnpm run dev"
    environment:
      # WEB SERVER
      - NODE_ENV=local
      - PORT=3001
      # DATABASE
      - DATABASE_URL=postgres://bitly_clone:password@db:5432/bitly_clone?connect_timeout=300

volumes:
  db:
