version: '3.8'

services:
  db:
    image: 'postgres:15'
    volumes:
      - 'db:/var/lib/postgresql/data'
    ports:
      - '5432:5432' #host:container
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=bitly_clone
      - POSTGRES_PASSWORD=password

  api:
    depends_on:
      - 'db'
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - '5000:5000' #host:container
    volumes:
      - ./api:/app
    command: bash -c "pnpm install && npx prisma generate && pnpm run dev"
    environment:
      # WEB SERVER
      - NODE_ENV=local
      - PORT=5000
      # DATABASE
      - DATABASE_URL=postgres://bitly_clone:password@db:5432/bitly_clone
      # LINK TRACKER APP(REDIRECTIONS)
      - SHORT_LINKS_BASE_URL=http://localhost:8000
  link_tracker:
    depends_on:
      - 'db'
    build:
      context: ./link_tracker
      dockerfile: Dockerfile.dev
    ports:
      - '8000:8000' #host:container
    volumes:
      - ./link_tracker:/app
    command: bash -c "pnpm install && npx prisma generate && pnpm run dev"
    environment:
      # WEB SERVER
      - NODE_ENV=local
      - PORT=8000
      # DATABASE
      - DATABASE_URL=postgres://bitly_clone:password@db:5432/bitly_clone

volumes:
  db:
